services:
  frontend:
    image:
        iztokkucan/sxo-token-grabber:0.0.1
    environment:
      SAXO_USER: 17805023
      SAXO_PASS: c45o55am 
      TOKEN_PATH: /tokendir
      TOKEN_FILE: saxo_token
    volumes:
      - type: bind
        source: /tmp/
        target: /tokendir/
