---
services:
    frontend:
        image: iztokkucan/sxo-token-grabber:0.0.1
        environment:
            SAXO_USER: 18033935
            SAXO_PASS: sfo859c1
            TOKEN_PATH: /tokendir
            TOKEN_FILE: saxo_token
        volumes:
            - type: bind
              source: /data/
              target: /tokendir/
