---
services:
    frontend:
        image: iztokkucan/sxo-token-grabber:0.2.0
        environment:
            SAXO_USER: 18286731
            SAXO_PASS: t62455gu
            TOKEN_PATH: /tokendir
            TOKEN_FILE: saxo_token
        volumes:
            - type: bind
              source: /data/
              target: /tokendir/
