version: '3.8'

services:
    redis:
        image: redis/redis-stack-server:latest
        container_name: redis-cache
        hostname: redis
        networks:
            - simple-strat-network

        restart: always
        ports:
            - 6379:6379

        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-stack-server
        volumes:
            - type: bind
              source: /workstem/sxo-work/packaging/docker/targets/simple-sys/redis-stack.conf
              target: /opt/redis-stack/etc/redis-stack.conf
              read_only: true
            - type: bind
              source: /data/cache
              target: /var/lib/redis-stack

    # redis insight
    redis-insight:
        depends_on:
            redis:
                condition: service_started

        # docker run --cap-add=IPC_LOCK -p 5000:5000 iztokkucan/redisinsight:2.34.0
        image: iztokkucan/redisinsight:2.34.0
        container_name: redis-insight
        hostname: redis-insight
        networks:
            - simple-strat-network

        restart: always
        ports:
            - 5000:5000
        cap_add:
            - IPC_LOCK

# -----
# unrelated, just here for convenience
            # SAXO_USER: 18286731
            # SAXO_PASS: t62455gu
# -----

    # when you have the token, start the data feeds
    data-feed:
        depends_on:
            redis:
                condition: service_started

        image: iztokkucan/simple-strat-data-feed:0.2.3
        container_name: feed-server
        networks:
            - simple-strat-network

        environment:
            TOKEN_FILE: /token
            INSTRUMENTS: FxSpot::GBPUSD,FxSpot::GBPCAD,FxSpot::GBPEUR,FxSpot::EURJPY,FxSpot::USDJPY,FxSpot::GBPJPY,FxSpot::AUDJPY,FxSpot::AUDEUR,FxSpot::AUDGBP,FxSpot::AUDUSD
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASS: boss

        volumes:
            - type: bind
              source: /data/saxo_token
              target: /token
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 10000
                #delay: 1s
                #window: 1s

networks:
  simple-strat-network:
    external: false
    name: simple-strat-network