---
version: '3.9'

services:
    redis:
        image: redis/redis-stack-server:latest
        container_name: redis-cache
        hostname: redis

        restart: always
        ports:
            - 6379:6379

        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-stack-server
        volumes:
            - type: bind
              source: /workstem/sxo-ifc/packaging/docker/targets/simple-sys/redis-stack.conf
              target: /opt/redis-stack/etc/redis-stack.conf
              read_only: true
            - type: bind
              source: /data/cache
              target: /var/lib/redis-stack

  # when you have the token, start the data feeds
    data-feed:
        depends_on:
            redis:
                condition: service_started

        image: iztokkucan/simple-strat-data-feed:0.2.0
        container_name: feed-server
        environment:
            TOKEN_FILE: /token
            INSTRUMENTS: FxSpot::GBPUSD,FxSpot::GBPCAD,FxSpot::GBPEUR,FxSpot::GBPJPY
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASS: boss

        volumes:
            - type: bind
              source: /data/saxo_token
              target: /token
        deploy:
            restart_policy:
                condition: on-failure
                delay: 1s
                max_attempts: 10000
                window: 1s

