# -------------------------------------------------------
# -------------------------------------------------------
FROM iztokkucan/sxo-base:0.2.3

USER root

RUN rm -Rf /scratch
RUN mkdir -p /scratch
WORKDIR /scratch

COPY strat.py /scratch
COPY strat.sh /scratch
RUN chmod ugo+x /scratch/strat.sh
ENV PATH=$PATH:/opt/mambaforge/bin
RUN . /root/.bashrc && mamba init

ENTRYPOINT ["/scratch/strat.sh"]
