---
version: '3.9'

services:
    cache:
        image: redis/redis-stack-server:latest
        container_name: redis-cachex
        hostname: redis-cachex

        restart: always
        ports:
            - 6379:6379

        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-statck-server --save 20 1 --loglevel warning
        volumes:
            - type: bind
              source: /data/cache
              target: /data/

        deploy:
            restart_policy:
                condition: any
