---
version: '3.9'

services:
    redis:
        image: redis/redis-stack-server:latest
        container_name: redis-cache
        hostname: redis

        restart: always
        ports:
            - 6379:6379

        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-stack-server
        volumes:
            - type: bind
              source: /workstem/sxo-ifc/packaging/docker/targets/simple-sys/redis-stack.conf
              target: /opt/redis-stack/etc/redis-stack.conf
              read_only: true
            - type: bind
              source: /data/cache
              target: /var/lib/redis-stack

  # when you have the token, start the data feeds
    data-feed:
        depends_on:
            redis:
                condition: service_started

        image: iztokkucan/sxo-data-feeds:0.0.4
        container_name: feed-server
        environment:
            TOKEN_FILE: /tokendir/saxo_token
            INSTRUMENTS: FxSpot::GBPUSD,FxSpot::GBPCAD,FxSpot::GBPEUR,FxSpot::GBPJPY
        volumes:
            - type: bind
              source: /tmp/
              target: /tokendir/
            - type: bind
              source: /data/
              target: /data/
        deploy:
            restart_policy:
                condition: on-failure
                delay: 1s
                max_attempts: 100
                window: 60s

