---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
          - id: check-yaml
          - id: check-json
            exclude: .vscode/
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: pretty-format-json
            args: [--autofix]
            exclude: .vscode/

    # - repo: https://gitlab.com/bmares/check-json5
    #   rev: v1.0.0(no mypy cache directory
    #   hooks:
    #       - id: check-json5


    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            args: [--line-length=140]

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports

    - repo: https://github.com/pycqa/flake8.git
      rev: 6.0.0
      hooks:
          - id: flake8
            args: [--max-line-length=140]
            additional_dependencies: [flake8-bugbear]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.2.0
      hooks:
          - id: mypy
            args: [--ignore-missing-imports, --install-types, --non-interactive]
            exclude: packaging

    # - repo: https://github.com/nbQA-dev/nbQA
    #   rev: 1.3.1
    #   hooks:
    #       - id: nbqa-black
    #       - id: nbqa-check-ast
    #       - id: nbqa-flake8
    #       - id: nbqa-pyupgrade
    #         args: [--py36-plus]
    #       - id: nbqa-isort

    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.31.0
      hooks:
          - id: yamllint
            args: [-c=.yaml_lint.yaml]
