---
package:
    name: ik.sxo
    version: v0.3.0

source:
    path: ../../

build:
    include_recipe: false

    skip: true # [py<39]

    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python             ==3.11.6
        - setuptools_scm     >=1.1.6

    run:
        - python             ==3.11.6
        - aiohttp            >=3.8.6
        - numpy              >=1.24.4
        - numba              >=0.57.1
        - pandas             >=2.1.1
        - websockets         >=11.0.3
        - redis-py           >=5.0.1
        - pyarrow            >=13.0.0
        - clickhouse-connect >=0.6.23

about:
    home: iztokkucan.io
    licence: MIT
