---
package:
    name: ik.sxo
    version: v0.2.0

source:
    path: ../../

build:
    include_recipe: false

    skip: true # [py<39]

    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python            ==3.11.6
        - setuptools_scm    >=1.1.6

    run:
        - python            ==3.11.6
        - aiohttp           >=3.8.6
        - numpy             >=1.26.0
        - pandas            >=2.1.1
        - websockets        >=11.0.3
        - redis-py          >=5.0.1

about:
    home: iztokkucan.io
    licence: MIT
