---
version: '3.9'

services:
    data-feed:
        image: redis/redis-stack-server:latest
        container_name: redis-cache
        hostname: redis

        restart: always
        ports:
            - 6379:6379

        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-stack-server
        volumes:
            - type: bind
              source: /workstem/sxo-ifc/packaging/docker/targets/simple-sys/redis-stack.conf
              target: /opt/redis-stack/etc/redis-stack.conf
              read_only: true
            - type: bind
              source: /data/cache
              target: /var/lib/redis-stack

        # deploy:
        #     restart_policy:
        #         condition: any
