# -------------------------------------------------------
# -------------------------------------------------------
FROM iztokkucan/pybase:0.0.1

USER root

RUN mkdir -p /scratch
RUN rm -f /scratch/*
WORKDIR /scratch

# COPY grab.py /scratch
# COPY mainline.sh /scratch
# RUN chmod ugo+x /scratch/mainline.sh

# USER selenium
# ENTRYPOINT ["/scratch/mainline.sh"]