# running with Docker Compose version 2.17.2, needs post 1.28
version: "3.9"

services:
  # generate a new 24hr loing token
  token_grabber:
    image:
        iztokkucan/sxo-token-grabber:0.0.1
    environment:
      SAXO_USER: 17541206
      SAXO_PASS: h3f046da 
      TOKEN_PATH: /tokendir
      TOKEN_FILE: saxo_token
    volumes:
      - type: bind
        source: /tmp/
        target: /tokendir/

  # when you have the token, start the data feeds
  feed:
    depends_on:
      token_grabber:
        condition: service_completed_successfully
    image:
        iztokkucan/sxo-data-feeds:0.0.2
    environment:
      TOKEN_FILE: /tokendir/saxo_token
      DATA_DIR: /data
      INSTRUMENTS: GBPUSD,GBPCAD,GBPBRL,GBPEUR,GBPJPY,GBPCNY,USDGBP,USDCAD,USDBRL,USDJPY,USDCNY,EURUSD,EURCAD,EURBRL,EURJPY,EURCNY
    volumes:
      - type: bind
        source: /tmp/
        target: /tokendir/
      - type: bind
        source: /data/
        target: /data/
    deploy:
        restart_policy:
            condition: on-failure
            delay: 1s
            max_attempts: 100
            window: 60s
  