# -*- coding: utf-8 -*-
# file generated by setuptools_scm
# don't change, don't track in version control
version = "0.0.2.dev10+g665db9d.d20220504083202"
version_tuple = (0, 0, 2, "dev10", "g665db9d.d20220504083202")
